In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('swiggy_food_delivery.csv')
df.head()

,Order_ID,Order_Date,Order_Time,Delivery_Date,Customer_ID,Restaurant_ID,Restaurant_Name,City,Cuisines,Food_Category,...,Order_Value,Discount,Delivery_Charges,Tax,Net_Revenue,Payment_Method,Order_Status,Delivery_Time,Delivery_Distance,Customer_Rating
0,SWG33554,2025-02-16,21:40,2025-02-16,CUST15279,REST204,Tycoon,Visakhapatnam,Hyderabadi,Pizza,...,291,14.55,35,13.82,325.27,UPI,Delivered,40,6.9,5.0
1,SWG09428,2025-06-06,22:08,2025-06-06,CUST20334,REST950,Kosha Mangsho,Kolkata,Hyderabadi,Breakfast,...,164,16.40,0,7.38,154.98,UPI,Delivered,26,2.9,4.0
2,SWG00200,2025-06-01,18:37,2025-06-01,CUST16875,REST253,Anand Sweets,Bengaluru,Street Food,South Indian,...,975,0.00,30,48.75,1053.75,UPI,Delivered,38,5.6,5.0
3,SWG12448,2025-01-12,17:15,2025-01-12,CUST20741,REST533,Dindigul Thalappakatti,Chennai,South Indian,Snacks,...,134,6.70,0,6.37,133.67,UPI,Delivered,20,2.1,5.0
4,SWG39490,2026-08-16,20:59,2026-08-16,CUST24249,REST928,Sagar Ratna,Delhi,Andhra,Biryani,...,378,0.00,30,18.90,426.90,UPI,Delivered,38,6.7,3.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           50000 non-null  object
 1   Order_Date         50000 non-null  object
 2   Order_Time         50000 non-null  object
 3   Delivery_Date      50000 non-null  object
 4   Customer_ID        50000 non-null  object
 5   Restaurant_ID      50000 non-null  object
 6   Restaurant_Name    50000 non-null  object
 7   City               50000 non-null  object
 8   Cuisines           50000 non-null  object
 9   Food_Category      50000 non-null  object
 10  Quantity           50000 non-null  int64
 11  Order_Value        50000 non-null  int64
 12  Discount           50000 non-null  float64
 13  Delivery_Charges   50000 non-null  int64
 14  Tax                50000 non-null  float64
 15  Net_Revenue        50000 non-null  float64
 16  Payment_Method     50000 non-null  object
 17  Order_Status       50000 non-null  object
 18  Delivery_Time      50000 non-null  int64
 19  Delivery_Distance  50000 non-null  float64
 20  Customer_Rating    46513 non-null  float64
dtypes: float64(5), int64(4), object(12)
memory usage: 8.0+ MB

In [4]:
df.describe()

,Quantity,Order_Value,Discount,Delivery_Charges,Tax,Net_Revenue,Delivery_Time,Delivery_Distance,Customer_Rating
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,46513.000000
mean,2.020720,525.580120,42.270127,29.969900,24.165951,537.445844,33.731800,5.504582,4.113345
std,1.050882,369.746787,54.391739,14.302611,17.153151,360.453410,14.790393,3.642723,1.000413
min,1.000000,50.000000,0.000000,0.000000,1.880000,42.000000,0.000000,1.000000,1.000000
25%,1.000000,264.000000,0.000000,25.000000,12.100000,283.550000,26.000000,2.800000,4.000000
50%,2.000000,419.500000,26.500000,30.000000,19.230000,434.020000,33.000000,4.700000,4.000000
75%,3.000000,685.000000,59.250000,35.000000,31.450000,690.450000,41.000000,7.400000,5.000000
max,5.000000,3295.000000,686.000000,70.000000,164.750000,3484.750000,100.000000,20.000000,5.000000

In [5]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Time', 'Delivery_Date', 'Customer_ID',
       'Restaurant_ID', 'Restaurant_Name', 'City', 'Cuisines', 'Food_Category',
       'Quantity', 'Order_Value', 'Discount', 'Delivery_Charges', 'Tax',
       'Net_Revenue', 'Payment_Method', 'Order_Status', 'Delivery_Time',
       'Delivery_Distance', 'Customer_Rating'],
      dtype='object')

## Let's find Unique values of some of the columns:
---

In [6]:
for column in ['City', 'Cuisines', 'Food_Category','Payment_Method', 'Order_Status']:
    print(f"{column}:")
    print("Unique Count:", df[column].nunique())
    print("Unique Values:", df[column].unique())
    print('-' * 50)

City:
Unique Count: 8
Unique Values: ['Visakhapatnam' 'Kolkata' 'Bengaluru' 'Chennai' 'Delhi' 'Mumbai'
 'Hyderabad' 'Pune']
--------------------------------------------------
Cuisines:
Unique Count: 15
Unique Values: ['Hyderabadi' 'Street Food' 'South Indian' 'Andhra' 'Pizza' 'Fast Food'
 'Burgers' 'Desserts' 'Chinese' 'Biryani' 'Healthy Food' 'North Indian'
 'Punjabi' 'Seafood' 'Mughlai']
--------------------------------------------------
Food_Category:
Unique Count: 20
Unique Values: ['Pizza' 'Breakfast' 'South Indian' 'Snacks' 'Biryani' 'Street Food'
 'Burgers' 'Punjabi' 'Healthy Food' 'Fast Food' 'North Indian' 'Seafood'
 'Chinese' 'Hyderabadi' 'Andhra' 'Bakery' 'Mughlai' 'Beverages' 'Desserts'
 'Ice Cream']
--------------------------------------------------
Payment_Method:
Unique Count: 4
Unique Values: ['UPI' 'Wallet' 'Card' 'Cash']
--------------------------------------------------
Order_Status:
Unique Count: 3
Unique Values: ['Delivered' 'Delayed' 'Cancelled']
--------------------------------------------------

In [7]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors = 'coerce')

In [8]:
df['Order_Date'].dtype

dtype('<M8[ns]')

### Now we need to look into "Customer_Rating" column, as it has 3487 null values:
---

In [9]:
df['Customer_ID'].nunique()

14479

In [10]:
df.duplicated(subset=['Customer_ID']).sum()

35521

In [11]:
len(df[df['Order_Status'] == 'Cancelled'])

3487

## Here, customer Rating is null where order was cancelled. So, no need to touch it, as it is also very important from Business view.
---

In [12]:
pd.crosstab(df['Order_Status'],df['Customer_Rating'].isna())

Customer_Rating  False  True
Order_Status
Cancelled            0   3487
Delayed           2560      0
Delivered        43953      0

# So, There is no Business Problem with this situation
---

In [16]:
df['Year'] = df['Order_Date'].dt.year
df['month_Number'] = df['Order_Date'].dt.month
df['Month'] = df['Order_Date'].dt.month_name()

In [17]:
df

,Order_ID,Order_Date,Order_Time,Delivery_Date,Customer_ID,Restaurant_ID,Restaurant_Name,City,Cuisines,Food_Category,...,Tax,Net_Revenue,Payment_Method,Order_Status,Delivery_Time,Delivery_Distance,Customer_Rating,Year,month_Number,Month
0,SWG33554,2025-02-16,21:40,2025-02-16,CUST15279,REST204,Tycoon,Visakhapatnam,Hyderabadi,Pizza,...,13.82,325.27,UPI,Delivered,40,6.9,5.0,2025,2,February
1,SWG09428,2025-06-06,22:08,2025-06-06,CUST20334,REST950,Kosha Mangsho,Kolkata,Hyderabadi,Breakfast,...,7.38,154.98,UPI,Delivered,26,2.9,4.0,2025,6,June
2,SWG00200,2025-06-01,18:37,2025-06-01,CUST16875,REST253,Anand Sweets,Bengaluru,Street Food,South Indian,...,48.75,1053.75,UPI,Delivered,38,5.6,5.0,2025,6,June
3,SWG12448,2025-01-12,17:15,2025-01-12,CUST20741,REST533,Dindigul Thalappakatti,Chennai,South Indian,Snacks,...,6.37,133.67,UPI,Delivered,20,2.1,5.0,2025,1,January
4,SWG39490,2026-08-16,20:59,2026-08-16,CUST24249,REST928,Sagar Ratna,Delhi,Andhra,Biryani,...,18.90,426.90,UPI,Delivered,38,6.7,3.0,2026,8,August
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,SWG11285,2025-07-08,14:52,2025-07-08,CUST16316,REST144,Cafe Madras,Mumbai,Burgers,Biryani,...,18.20,412.20,UPI,Delivered,28,3.7,2.0,2025,7,July
49996,SWG44733,2025-11-25,13:49,2025-11-25,CUST14750,REST849,Buhari Hotel,Chennai,South Indian,Hyderabadi,...,35.10,737.10,UPI,Cancelled,0,2.2,NaN,2025,11,November
49997,SWG38159,2026-05-17,10:11,2026-05-17,CUST23878,REST247,Vista,Visakhapatnam,Pizza,Chinese,...,36.75,796.75,UPI,Delivered,29,1.2,4.0,2026,5,May
49998,SWG00861,2025-01-25,16:23,2025-01-25,CUST12281,REST676,Wangs Kitchen,Chennai,Street Food,Beverages,...,11.50,276.40,UPI,Delivered,37,3.9,5.0,2025,1,January
49999,SWG15796,2026-04-22,18:34,2026-04-22,CUST13969,REST208,Anjappar,Chennai,South Indian,Ice Cream,...,16.67,385.12,UPI,Delivered,29,6.0,5.0,2026,4,April

## Let's connect to mysql and further to PowerBI:
---

In [19]:
df.to_csv('swiggy_fd_cleaned.csv',index = False)

In [20]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in C:\Users\dhira\anaconda3\envs\Data_Analysis\Lib\site-packages (1.2.3)
Requirement already satisfied: sqlalchemy in C:\Users\dhira\anaconda3\envs\Data_Analysis\Lib\site-packages (2.1.3)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\dhira\anaconda3\envs\Data_Analysis\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
# pandas already available here
from sqlalchemy import create_engine

In [22]:
# Getting new cleaned dataframe in df1:
df1 = pd.read_csv('swiggy_fd_cleaned.csv')

In [23]:
# Creating Engine to connect to MySQL :

engine = create_engine('mysql+pymysql://root:Vjds%402020@localhost:3306/swiggydb')

In [24]:
# Now, Let's Connect :
df1.to_sql(name = 'swiggy_data', con = engine, if_exists = 'replace', index = False)

50000