In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv('Details.csv')
df2 = pd.read_csv('Orders.csv')

In [4]:
df1.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [5]:
df2.head()

  Order ID  Order Date CustomerName           State     City
0  B-26055  10-03-2018    Harivansh   Uttar Pradesh  Mathura
1  B-25993  03-02-2018       Madhav           Delhi    Delhi
2  B-25973  24-01-2018  Madan Mohan   Uttar Pradesh  Mathura
3  B-25923  27-12-2018        Gopal     Maharashtra   Mumbai
4  B-25757  21-08-2018     Vishakha  Madhya Pradesh   Indore

In [6]:
df1.shape

(1500, 7)

In [7]:
df2.shape

(500, 5)

In [9]:
df1['Order ID'].nunique()

500

In [10]:
df2['Order ID'].nunique()

500

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1500 non-null   object
 1   Amount        1500 non-null   int64
 2   Profit        1500 non-null   int64
 3   Quantity      1500 non-null   int64
 4   Category      1500 non-null   object
 5   Sub-Category  1500 non-null   object
 6   PaymentMode   1500 non-null   object
dtypes: int64(3), object(4)
memory usage: 82.2+ KB

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    object
 1   Order Date    500 non-null    object
 2   CustomerName  500 non-null    object
 3   State         500 non-null    object
 4   City          500 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

# As the Dataset is already Cleaned, Let's move this to MySQL to connect to PowerBi
---

In [16]:
# Pandas already imported
!pip install pymysql sqlalchemy

Collecting pymysql
  Using cached pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: sqlalchemy in c:\users\dhira\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\dhira\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dhira\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Using cached pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [17]:
from sqlalchemy import create_engine

In [18]:
engine = create_engine('mysql+pymysql://root:Vjds%402020@localhost:3306/ecomdb')

In [19]:
df1.to_sql(name = 'details', con = engine, if_exists = 'replace', index = False)

1500

In [20]:
df2.to_sql(name = 'orders',  con = engine, if_exists = 'replace', index = False)

500